- name: Install php-fpm & php extensions
  become: true
  pacman: pkg={{ item }} state=installed update_cache=true
  with_items:
  - php-fpm
  - php-gd

- name: Configure php-fom with apache2
  become: true
  copy: src=files/www.conf dest=/etc/php/7.2/fpm/pool.d/

- name: Restart php-fpm
  become: yes
  service: name=php-fpm state=restarted
