- name: Install apache2 web server
  become: true
  pacman: pkg={{ item }} state=installed update_cache=true
  with_items:
  - apache
  
- name: Upload apache2 default configuration
  become: yes
  copy: src=files/000-default.conf dest=/etc/apache2/sites-enabled/

- name: Remove default apache2 index.html file
  become: yes
  file:
    state: absent
    path: /var/www/html/index.html

- name: Upload default index.php for host 
  become: yes
  copy: src=files/index.php dest=/var/www/html/ mode=0644  

- name: Restart webserver
  become: yes
  service: name=httpd state=restarted